version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
  nest_application:
    container_name: nest_application
    restart: always
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - my_network
    ports:
      - ${APP_PORT}:${APP_PORT}
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
    - my_network
    ports:
      - '5050:80'
    depends_on:
        - postgres

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
